# This file was generated by GoReleaser. DO NOT EDIT.
cask "codify" do
  name "codify"
  desc "MCP server & CLI that generates context, specs, and skills for AI coding agents"
  homepage "https://github.com/jorelcb/codify"
  version "1.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codify"

  on_macos do
    on_intel do
      url "https://github.com/jorelcb/codify/releases/download/v#{version}/codify_#{version}_darwin_amd64.tar.gz"
      sha256 "8c2d3166cf7be260f753658cdc7afdfd683d92b19ce811ea4eca06d1bef3d5c4"
    end
    on_arm do
      url "https://github.com/jorelcb/codify/releases/download/v#{version}/codify_#{version}_darwin_arm64.tar.gz"
      sha256 "c4a5897b28e829cf7c84405b00903b773948f38fc1ed33e37956e8fdeafe3edd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jorelcb/codify/releases/download/v#{version}/codify_#{version}_linux_amd64.tar.gz"
      sha256 "bca0c2b82688bf5799ae33e2dcee3912d9c6e77b8f212f15e90e0e82da4619f9"
    end
    on_arm do
      url "https://github.com/jorelcb/codify/releases/download/v#{version}/codify_#{version}_linux_arm64.tar.gz"
      sha256 "8eccae27e0ea40a82b0c093a252dd4c9d61c1986c292e8715e75070e659fdf08"
    end
  end

  # No zap stanza required
end
