# This file was generated by GoReleaser. DO NOT EDIT.
cask "codify" do
  name "codify"
  desc "MCP server & CLI that generates context, specs, and skills for AI coding agents"
  homepage "https://github.com/jorelcb/codify"
  version "1.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "codify"

  on_macos do
    on_intel do
      url "https://github.com/jorelcb/codify/releases/download/v#{version}/codify_#{version}_darwin_amd64.tar.gz"
      sha256 "2cbb6f2cea1d9875c136e6246330c21f50a5bc2053084bd8b1c7beef221a6d15"
    end
    on_arm do
      url "https://github.com/jorelcb/codify/releases/download/v#{version}/codify_#{version}_darwin_arm64.tar.gz"
      sha256 "c99ae95176d07db2d64e421e4acd07912be2499e7843bc068176f01b8126b25f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jorelcb/codify/releases/download/v#{version}/codify_#{version}_linux_amd64.tar.gz"
      sha256 "788ef901948c94033149880cac4c0f54d4ba296e32c7189b882910061b12c6b5"
    end
    on_arm do
      url "https://github.com/jorelcb/codify/releases/download/v#{version}/codify_#{version}_linux_arm64.tar.gz"
      sha256 "d479b799382ec02aefc2ab048753facb6aa6e7435d8b42120dde07f6fd54d8ef"
    end
  end

  # No zap stanza required
end
