# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codify < Formula
  desc "MCP server & CLI that generates context, specs, and skills for AI coding agents"
  homepage "https://github.com/jorelcb/codify"
  version "2.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jorelcb/codify/releases/download/v2.1.1/codify_2.1.1_darwin_amd64.tar.gz"
      sha256 "7b12c1b54c5649275a576a7454de45e33966353712c0348c33df700fb40af539"

      define_method(:install) do
        bin.install "codify"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jorelcb/codify/releases/download/v2.1.1/codify_2.1.1_darwin_arm64.tar.gz"
      sha256 "b40a586cb3368ce9cc42be5a869aeb990ec06e79a2aff4dbd46071da52579d57"

      define_method(:install) do
        bin.install "codify"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorelcb/codify/releases/download/v2.1.1/codify_2.1.1_linux_amd64.tar.gz"
      sha256 "59eb5faa307d3c76d296e33dc67a94881a04062ee80a7594cf93fd3cfdf1b5a3"
      define_method(:install) do
        bin.install "codify"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorelcb/codify/releases/download/v2.1.1/codify_2.1.1_linux_arm64.tar.gz"
      sha256 "e184a0e88b1bf11096548f0d31ed8b596fbe97feff2853e125ab93c1885d20d4"
      define_method(:install) do
        bin.install "codify"
      end
    end
  end

  test do
    system "#{bin}/codify", "--version"
  end
end
